name: BuildFrontVue

on:
  push:
    branches: [ master ]
    paths: 
      - 'FrontEnd/effort-extension-vue/**/*'
  pull_request:
    branches: [ master ]
    paths: 
      - 'FrontEnd/effort-extension-vue/**/*'
jobs:

  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build and push Docker images
      uses: docker/build-push-action@v1.1.0      
      with:
        # Username used to log in to a Docker registry. If not set then no login will occur
        username: iloer
        # Password or personal access token used to log in to a Docker registry. If not set then no login will occur
        password: ${{ secrets.DOCKERHUBPASSWORD }}
        # Docker repository to tag the image with
        repository: shtormtech/azure-effort-extension-front-vue
        # Comma-delimited list of tags. These will be added to the registry/repository to form the image's tags
        tags: latest
        # Automatically tags the built image with the git reference as per the readme
        tag_with_ref: true
        # Path to the build context
        path: './FrontEnd/effort-extension-vue'
        # Path to the Dockerfile (Default is '{path}/Dockerfile')
        dockerfile: 'FrontEnd/effort-extension-vue/Dockerfile'
        # Comma-delimited list of labels to add to the built image
        labels: 'AzureDevOps'
        # Whether to push the image
        push: true
